"""Structured data contract for SentryQuery answers.

AnswerSchema is the single structured object every answer is packaged into. It
is produced at the final synthesis step (see run_query in sentry_query.py) and
consumed by both the Streamlit UI and — from Layer 2 on — the Critic agent.

Keeping this in its own module lets the agent code and the Critic import the
same contract without a circular dependency.
"""
from typing import Literal

from pydantic import BaseModel, Field


class AnswerSchema(BaseModel):
    """The final answer, structured.

    `answer` and `confidence` are model-derived at synthesis time. `sources` and
    `tool_used` are set authoritatively from the agent's captured run state
    (the exact retrieved chunks and which tools actually fired), NOT free-
    generated by the model — so citations cannot be hallucinated.
    """

    answer: str = Field(description="The final answer text shown to the user.")
    sources: list[str] = Field(
        default_factory=list,
        description="Citations: 'filename p.N' for document chunks, or URLs for web results.",
    )
    tool_used: Literal["docs", "web", "none"] = Field(
        description="Which tool primarily produced the answer: docs, web, or none."
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Model's self-assessed 0-1 confidence that the answer is supported by the sources.",
    )


class CriticVerdict(BaseModel):
    """The Critic's groundedness ruling on a drafted answer (Layer 2).

    The Critic verifies the draft against the exact chunks the Researcher
    retrieved. APPROVE means every claim is supported; REVISE means at least one
    claim is not, and `reason` should name the specific unsupported claim.
    """

    verdict: Literal["APPROVE", "REVISE"] = Field(
        description="APPROVE if every claim is grounded in the sources; REVISE otherwise."
    )
    reason: str = Field(
        description="If REVISE, the specific unsupported/overreaching claim; if APPROVE, a brief confirmation.",
    )
